### ISSUE TITLE
creat-fullset not working when providing SOURCE_SNAPSHOT_STACK_PREFIX

### ISSUE THREAD

**Issue by engshine** [shinesolutions/aem-opencloud-manager#25]
There is a missing environment variable not set in the pipeline:
env.AOC_CONFIG_PROFILE_DIR_AEM_AWS_STACK_BUILDER

which is needed by GenerateOfflineSnapshotConfig.groovy, as it's empty a null value is substituted causing the job to fail.

**Comment by mbloch1986** [comment]
Fixed with version 4.0.0-pre.2
